import os

GAME_WIDTH = 600
GAME_HEIGHT = 400
BALL_RADIUS = 10
PLAYER_RADIUS = 15
COLLISION_DISTANCE = BALL_RADIUS + PLAYER_RADIUS

# Physics
BALL_FRICTION = 0.99
BALL_KICK_FORCE = 0.1
BALL_RESET_X = GAME_WIDTH // 2
BALL_RESET_Y = GAME_HEIGHT // 2

# Boundaries
BOUNDARY_PADDING = 10
MIN_X = BOUNDARY_PADDING
MAX_X = GAME_WIDTH - BOUNDARY_PADDING
MIN_Y = BOUNDARY_PADDING
MAX_Y = GAME_HEIGHT - BOUNDARY_PADDING

# Game loop
UPDATE_RATE = 60  # FPS
UPDATE_INTERVAL = 1 / UPDATE_RATE

# Game rooms
MAX_ROOMS = 100
MAX_PLAYERS_PER_ROOM = 4
ROOM_CODE_LENGTH = 4
ROOM_CODE_CHARS = 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789'  # No confusing characters
ROOM_INACTIVITY_TIMEOUT = 1800  # 30 minutes in seconds

# Server
DEFAULT_PORT = 5000
SECRET_KEY = os.getenv('SECRET_KEY', 'secret!')
